### PR TITLE
Move configuration docs

### PR DESCRIPTION
**Pull request by fg-j**
## Summary

Move buildpack configuration docs from reference to How To section, since the content is outcome-oriented.

## Checklist

* [ ] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [ ] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by fg-j** [comment]
Waiting for #308 to merge.

**Comment by fg-j** [comment]
Check links is failing because [the edit on github button on the rendered site doesn't point to a real URL (yet)](https://github.com/paketo-buildpacks/paketo-website/pull/317/checks?check_run_id=3680998575#step:6:37).

I think this should be good to merge anyway. Maybe it's a signal the link checker needs another thing added to its excludelist...

**Review by ForestEckhardt — CHANGES_REQUESTED** [review]
I would prefer that the link is added to the exclude list before merging this to help prevent confusion on future PRs

**Comment by fg-j** [comment]
@ForestEckhardt i've added a [commit](https://github.com/paketo-buildpacks/paketo-website/pull/317/commits/24763ae0304adb4c81ecc81e6483e660fab7fab8) to update the excludelist. Should be good to go now.

**Review by ForestEckhardt — APPROVED** [review]

**Pull request merged**
