### PR TITLE
Phase 1 website redesign

### LINKED ISSUE #176: Update deploy.yml workflow to use peaceiris/actions-hugo@v2 GHA
## Summary
Instead of manually installing Hugo via a shell script in the `deploy.yml` workflow we should switch to use [peaceiris/actions-hugo@v2](https://github.com/peaceiris/actions-hugo) like we do in the `v2.yml` workflow as part of the staging site deployment. This will allow us to more easily keep up to date with the latest version of hugo.

See the [v2.yml](https://github.com/paketo-buildpacks/paketo-website/blob/6236a386ea02c7e1d84ef3bfd258e57609fd7abe/.github/workflows/v2.yml#L16-L20) workflow for and example

### PR DESCRIPTION
**Pull request by fg-j**
## Summary

This is the first phase of the redesign of the site following [this mockup](https://www.figma.com/file/vc91zvGMqGxY022FUoOm4S/Paketo_Web_0.01?node-id=57%3A34).

Also Resolves #176 

## Use Cases

Updated homepage copy, improved color scheme, better experience on mobile.

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [ ] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by fg-j** [comment]
From "GOLIVE CHECKLIST"

- [ ] Update robots.txt in v2 branch to allow indexing
- [ ] Add google analytics back into to header

**Comment by fg-j** [comment]
Please DO NOT SQUASH on merge. We'd like this commit history preserved so we can roll back small changes as needed.

**Comment by andymoe** [comment]
Can we get a LGTM :)

**Review by ForestEckhardt — APPROVED** [review]
👍

**Pull request merged**
