### PR TITLE
reorganize nodejs docs

### PR DESCRIPTION
**Pull request by fg-j**
## Summary

Part of #203 
- Splits the existing nodejs docs content into How To and Reference sections.
     - h2s in the How To section have been changed so they all make sense in a sentence like "How to ________"

@paketo-buildpacks/nodejs-maintainers please have a look and let me know if something jumps out as horribly wrong.

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by fg-j** [comment]
@paketo-buildpacks/content-maintainers let's wait to merge until we hear from some nodejs maintainers.

**Comment by fg-j** [comment]
@paketo-buildpacks/nodejs-maintainers nudge :)
how does this look to y'all?

**Comment by arjun024** [comment]
LGTM

**Comment by fg-j** [comment]
@paketo-buildpacks/content-maintainers please approve and merge

**Review by ForestEckhardt — APPROVED** [review]

**Pull request merged**
