### PR TITLE
Reworks colors and typography

### PR DESCRIPTION
**Pull request by ForestEckhardt**
- Also reweights the language family buildpacks to put them in
alphabetical order

Resolves issues #52 and #49

### CODE REVIEW

**Comment by ForestEckhardt** [comment]
I am just waiting on new assets.

**Comment by kvedurmu** [comment]
I'd like to get some more consensus here before we merge this. To me, the background changes on the Dashboard look great with the blue background. I feel that this looks weird on the docs page with the blue background and white around the docs sidebar.
image

Also, couple small things I noticed:
- The view output button looks a lot closer than it currently is (it looks like a single word)
image

- The "Get Started" text on the homepage is still a link. The mock in the issue shows this as a button

**Comment by sampeinado** [comment]
I made an error in the mockup! The body text and the h2s should actually be 400 weight not 500. 

font-weight: normal;

**Comment by sampeinado** [comment]
I also didn't make clear that there is a change in element type happening. Where it says "What are Buildpacks?" and "Why Paketo Buildpacks?" they are now changed to h1s from h2s

**Comment by sampeinado** [comment]
Also, after our discussion two Fridays ago, I think it makes sense to implement the Get Started button to see how it affects conversion. That's comment 14 on the mockup. Thank you Forest !!

**Comment by kvedurmu** [comment]
General feedback (from comparing to the Figma mock):
- per the Figma, all subheading text on home page should be the Blue color (HEX `background: #4A516D;`). The "Your app, in your favorite..." is still black
- Could just be me, but the Get Started button seems too big compared to the mock. Maybe the real issue is that the hero section text is weighted differently than what's in the mock

We should get @sampeinado's feedback here as well before merging.

**Comment by ForestEckhardt** [comment]
@kvedurmu I change the hero tag line font color. As far as, I can tell from looking back and forth on my laptop the button we have is smaller if anything. I can change it if you like but I am going to need to know what you want.

**Comment by kvedurmu** [comment]
Feedback from Sam: 
- change weight of the Hero sub-heading text to have a weight of 300
- change the padding of the get started button to be 22 all around
- On the docs page, the title should be "PAKETO DOCS" instead of "Docs"

**Review by kvedurmu — APPROVED** [review]

**Pull request merged**
