### PR TITLE
Fixes code-output

### PR DESCRIPTION
**Pull request by ForestEckhardt**
- Previously you could not have a functional code-output block without
having a copyable block directly preceding it. This is now no longer
the case and you can have an output block anywhere in the docs.

You should be able to test this by adding a stand alone (meaning not directly following a `copyable` code block) `code-output` block to the current `main` branch and see that while a button appears you cannot interact with it and it will not toggle.

You should then be able to repeat that same process with the changes on this branch and the code block should function properly.

### CODE REVIEW

**Comment by fg-j** [comment]
@ForestEckhardt I made a change to the implementation that eliminates the need to change existing CSS. The key here is that `<pre>` is designed for [preformatted text](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre). If elements are inside of that tag that _aren't_ simply text, weird stuff starts to happen.

**Comment by ForestEckhardt** [comment]
@fg-j Fair enough. How do we want to proceed with this PR?

**Comment by fg-j** [comment]
Can you confirm for me that this implementation still works as you expected it to? If that's looking good I'm happy to approve.

**Comment by ForestEckhardt** [comment]
Works as expected thanks!

**Review by fg-j — APPROVED** [review]

**Pull request merged**
