### PR TITLE
Uncomments Jammy Full Stack details

### PR DESCRIPTION
**Pull request by ryanmoran**
## Summary

This was already added on the stacks page, but commented out. I've uncommented it.

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by ForestEckhardt** [comment]
I don't think that this is totally accurate around PHP and Ruby support.

**Comment by ryanmoran** [comment]
The stack can say that it is ideal for supporting those types of applications even though the buildpacks don't support the stack yet.

**Comment by ryanmoran** [comment]
Here's the thing. I'm not gonna remember to update this documentation when PHP and Ruby complete their Jammy support. If I leave them off, someone needs to go back and add them when that happens. Would you like to volunteer?

**Review by ForestEckhardt — APPROVED** [review]

**Comment by ForestEckhardt** [comment]
I think that the argument saying it is ideal to support those languages is fine for me.

**Pull request merged**
