### PR TITLE
Docs: Add python docs

### PR DESCRIPTION
**Pull request by arjun024**
This is being moved from
https://github.com/paketo-buildpacks/python/tree/d2534b0a0224d413439d098a99385cf3d661f61c/docs
as part of Python language-family's promotion to the Paketo buildpacks
org. See RFC 35
https://github.com/paketo-buildpacks/rfcs/blob/main/text/0035-python-promotion.md

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Review by ForestEckhardt — APPROVED** [review]
Looks fantastic

**Review by fg-j — CHANGES_REQUESTED** [review]
There are a couple of tweaks/polish changes I'd like to see before these docs go live. I'll add more individual comments // make a polish commit shortly.

**Comment by arjun024** [comment]
@ForestEckhardt @fg-j Per [RFC](https://github.com/paketo-buildpacks/rfcs/blob/main/text/0035-python-promotion.md), Python logo can be added to the homepage. I'll also try to add it in the meantime. Do you know if the image has some kind of a license requirement?

**Comment by fg-j** [comment]
@arjun024 not a clue re: Python logo licensing specifically. What I've found for other logos is that they are usually available as high quality SVGs in some kind of "branding kit" for the thing, and that the kit sometimes has guidelines about how/where the logo can be displayed.

**Comment by arjun024** [comment]
@fg-j I've added to homepage the Python logo from the Python Software foundation.

https://www.python.org/psf/trademarks-faq/:
> Q: May I use the Python logo for promotion?
A: This is fine as long as you use the unaltered Python logos from our website and don't claim an official affiliation with the PSF or the Python developers.

**Comment by fg-j** [comment]
@ForestEckhardt @arjun024 I added a polish commit here. Just wanted to point out a couple of things I did, for future use in writing/reviewing docs:

- I changed internal links to our documentation to `{{< ref >}}` and `{{< relref >}}` hugo shortcodes because these will [automatically fail the hugo build](https://gohugo.io/content-management/cross-references/#ref-and-relref-configuration) if they're broken.

- I used the how-to and reference executive summary [shortcodes](https://github.com/paketo-buildpacks/paketo-website/blob/dfa816f64abaaba02302b0f00fb45e94c3a953e0/layouts/shortcodes) so that we can easily keep the language of the executive summaries for all docs pages consistent.

- I removed the manually inserted section header hrefs because these are rendered automatically [by this markup rendering config](https://github.com/paketo-buildpacks/paketo-website/blob/dfa816f64abaaba02302b0f00fb45e94c3a953e0/layouts/_default/_markup/render-heading.html).

- I reworded the How To section's top-level headers to phrases that complete the sentence "How to ________" (e.g. How to Use a Package Manager), for consistency and clarity across How To docs.

**Review by fg-j — APPROVED** [review]

**Pull request merged**
