### PR TITLE
mobile-first implementation of table of contents

### LINKED ISSUE #185: Add auto generated table of contents to each docs page
# Summary
Right now each documentation page have a table of content however it is part of each individual page. We want to push this logic into its own partial that can be shared among all docs pages as a component and move the TOC above all page content.

The table of contents should include anchor links all headers in the doc. (We may want to limit the depth of the TOC to h3 and above or something like that)
 
image

### PR DESCRIPTION
**Pull request by fg-j**
## Summary

Resolves #185 

## Use Cases

The styling and spacing of the table of contents now matches the Figma. 

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by andymoe** [comment]
I think we still want the page title above the TOC per the mocks (plus it looks a bit strange to see a TOC with no context)

https://www.figma.com/file/vc91zvGMqGxY022FUoOm4S/Paketo_Web_0.01?node-id=619%3A2835

**Comment by fg-j** [comment]
There's a weird "double title" on the .NET Core docs page because I need to update the markdown for the page in the dotnet core repo to exclude the first-level markdown header. (https://paketo-staging--table-of-contents-89y3arbg.web.app/docs/buildpacks/language-family-buildpacks/dotnet-core/)

This will be fixed when [this PR](https://github.com/paketo-buildpacks/dotnet-core/pull/528) is merged and a release of the language family cut.

**Comment by andymoe** [comment]
ok, @fg-j, docs mostly looks look good now. The last issue I see is that we have a regression in the `edit on GitGub` button. Poor little octocat is squished now.

**Review by andymoe — APPROVED** [review]
whee, looks good!

**Pull request merged**
