### PR TITLE
Wording

### PR DESCRIPTION
**Pull request by jdubois**
## Summary

Simple wording issue

## Checklist

* [ ] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by jdubois** [comment]
This corrects a real issue, but this is more for me to go through the process of having the CLA validated at the Microsoft level, so I can contribute to more meaningful things in the future

**Comment by fg-j** [comment]
Hey @jdubois -- how's it going with getting the CLA validated? Is there anything the project can do to help grease the wheels?

**Comment by jdubois** [comment]
Hi, no update or anything, so it’s good to start with this experiment ! Next week I’ll try to find who’s in charge.

**Comment by jdubois** [comment]
Hi, I have signed the CLA individually, with the agreement from my management

**Comment by fg-j** [comment]
Please rebase if you would like to contribute this change!

**Comment by jdubois** [comment]
I rebased but I noticed this was already fixed, so no need to merge this anymore, closing!

**Pull request closed without merging**
