### PR TITLE
Show hide docs nav

### PR DESCRIPTION
**Pull request by andymoe**
## Checklist

* [ ] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [ ] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by andymoe** [comment]
PR DEPLOYED TO: https://paketo-staging--show-hide-docs-nav-201-n1yb79fh.web.app
SITE EXPIRES AT: 2021-07-12T04:19:19.935578372Z (in 72h)

**Comment by fg-j** [comment]
Moving to draft pending a discussion about UX design.

**Comment by ryanmoran** [comment]
Here are a couple of things I noticed. Not sure what's to be done about them, but just wanted to share what I saw:

1. The scrolling behavior can get into a weird state where you get stuck only being able to scroll the content behind the menu.
https://user-images.githubusercontent.com/155736/131753669-7f6eb961-23e1-4757-9810-5ffd3f1473a3.mov

2. The search autocomplete is pretty hard to read or use on mobile.
https://user-images.githubusercontent.com/155736/131753743-3a5116a5-55cc-4d28-84b0-009d67cc0451.mov

**Comment by fg-j** [comment]
I'm hoping to use "detached mode" for docs search on mobile. (See https://www.algolia.com/doc/ui-libraries/autocomplete/core-concepts/detached-mode) for explanation/screenshots. I think that would really improve the search UX on mobile. However, I haven't yet figured out how to configure the search to use detached mode. I've filed a support ticket with Algolia DocsSearch about this, and am waiting to hear back. They are allegedly "very busy".

For now, this PR is blocked on resolution of that support ticket.

**Comment by fg-j** [comment]
It's worth noting that it seems like others have experienced issues with DocSearch on mobile: https://github.com/algolia/docsearch/issues/181, https://github.com/algolia/docsearch/issues/851. 

I wonder whether it would be better to simply omit the search bar on mobile.

**Comment by fg-j** [comment]
Still have not heard back from Algolia support re: my request. I'm opting to move the search bar out of the collapsible nav tab for now. Hopefully this makes mobile search more useable.

**Comment by fg-j** [comment]
I've updated this to keep the search bar up by the header bar on mobile (like it is on paketo.io now). Still not amazing mobile search UX, but maybe good enough for now. @ryanmoran, does this mitigate the search issues for you?

**Comment by ryanmoran** [comment]
Yes. This looks fine to me.

**Comment by fg-j** [comment]
@ryanmoran or @ForestEckhardt, can one of you please approve/merge since I'm an author on this one?

**Review by ryanmoran — APPROVED** [review]

**Pull request merged**
