### PR TITLE
Refactor docs css

### LINKED ISSUE #192: Refactor docs HTML/CSS to use BEM naming and remove unused classes
## What happened?

* What were you attempting to do?
The HTML/CSS from the previous iteration of the site is still hanging around in this repo, and is still in use to govern the styling of much of the docs page. The nesting of the CSS and desktop-first design make it difficult to implement the desired changes for the redesign. This issue is to refactor the documentation HTML and CSS to reduce nesting, follow BEM naming conventions, and switch to mobile-first media queries.

### PR DESCRIPTION
**Pull request by fg-j**
## Summary

Resolves #192 

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [ ] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by andymoe** [comment]
Staging site for this PR is here: https://paketo-staging--refactor-docs-css-i8t3nu5p.web.app (for 72h or so time)

**Comment by andymoe** [comment]
I think this looks pretty good... the two issues I have are:
- When you click around on the side bar for docs the way the white selection box has been implemented moves the text around. This happened a bit prior to this PR however the for whatever reason it's especially noticeable on `docs->buildpacks->Configuring Paketo Buildpacks` because that nav item now splits across lines when selected. Ideally the text would not move when the white selection box UI is added.
- The second (smaller issue) is that the padding and font color of the output that appears when you click `VIEW OUTPUT` on pages like `Getting Started` is off. (We should probably not use blue for the text and have padding)

Feel free to push back if you think we should change these more incrementally... while they are a little annoying I'm not sure they are show stoppers if we sort them out quickly.

**Comment by fg-j** [comment]
The fixes you mentioned were pretty straightforward to address 🙂  @andymoe Have a look and see if things are looking better to you.

**Comment by andymoe** [comment]
@fg-j nice! It looks good to me. If you feel like squashing any of these commits please do so, otherwise I'll merge it as is in a couple hours after some morning appointments.

**Review by andymoe — APPROVED** [review]
looks good.

**Pull request merged**
