### PR TITLE
reorganize java documentation

### PR DESCRIPTION
**Pull request by fg-j**
## Summary

Part of #203 
- Splits the existing java docs content into How To and Reference sections.
     - h2s in the How To section have been changed so they all make sense in a sentence like "How to ________"
- Per an earlier conversation with @dmikusa-pivotal, the Java how-tos have been combined for Native Image and Java. The reference docs are separate. 

@paketo-buildpacks/java-buildpacks, since I have little context on  the inner workings of the Java buildpacks -- and don't know much about your prior docs writing process -- please let me know how this looks to you so far, and make edits/give feedback as needed. Ultimately, I think really fleshing out the Java how-tos will be a heavy lift. For now, I'm just going for accuracy, keeping things minimally confusing, and trying to get a separation of concerns between "Reference" and "How To" content.

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by dmikusa-pivotal** [comment]
@fg-j - Thanks! I asked David to take a look and provide some feedback tomorrow, so should have this shortly for you.

One question I have that comes to mind. Moving content is probably going to break URLs, right? Do we have any redirects in place to ensure that old URLs posted in Slack, README's, and other docs will remain unbroken?

**Comment by andymoe** [comment]
There should be “Hugo aliases” for all pages that have been moved so the
links should continue to work.

Might be worth us checking on “bookmark” names though which might be an
issue if a title of a section changes and was linked to from an
external source.

**Comment by pivotal-david-osullivan** [comment]
@fg-j The separation of the sections is great 🙌   

There are a couple of small things I noticed when reading over:

- On the 'Reference' page - there are some links that don't seem to be formed - one for [Paketo Java Buildpack], one for [Composite Buildpacks] and one for [BellSoft Liberica]
- On the 'How-To' page under 'Build from Source', there are some same-page anchors that are pointing to the old h2 title of 'Building from a Compiled Artifact' 

Looks good to me otherwise!

**Comment by fg-j** [comment]
@pivotal-david-osullivan I went in and cleaned up the things you pointed out. Good catches. I wasn't able to reproduce the issue you described with the Alibaba and Microsoft buildpacks links in the Alternative JVMs how-to section, though. Let me know if that is still happening for you.

**Review by andymoe — APPROVED** [review]

**Pull request merged**
