### PR TITLE
Reorganize web servers docs

### PR DESCRIPTION
**Pull request by fg-j**
## Summary

Part of #203 
- Splits the existing .NET docs content into How To and Reference sections. No new content has been added.
     - h2s in the How To section have been changed so they all make sense in a sentence like "How to ________"

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by fg-j** [comment]
@paketo-buildpacks/php-maintainers @paketo-buildpacks/web-servers-maintainers  Here's my first pass at splitting up existing docs. Feedback is welcome.


@paketo-buildpacks/content-maintainers let's wait a bit to hear from the language family maintainers

**Comment by arjun024** [comment]
@fg-j What's the criteria for what goes into `How-To`, and what goes into `Reference`?
My assumption was that `Reference` meant links and definitions if relevant. I worry this is just going to make the user search in two places and have redundant info (like supported versions, httpd.conf in this diff).

**Comment by dmikusa-pivotal** [comment]
Thoughts:

First, I don't think Nginx & HTTPD should be two top-level categories. I think you should have a "Web Servers" top-level group like you do for Java or Dotnet core. "Web Severs" IMHO is the language family and the categories seem to line up with the language family. 

>What's the criteria for what goes into How-To, and what goes into Reference?

I think most of what we have fits under how-to. It's task-related documentation. How to do XYZ (build an app, change a config setting, etc..)

Reference is similar, but the details. Things like what detection criteria are applied, what steps/logic are taken when the buildpack runs. What's the full list of configuration settings supported by a buildpack. 

>I worry this is just going to make the user search in two places and have redundant info (like supported versions, httpd.conf in this diff).

I have similar concerns. If the pages are not too large, I would prefer to have different sections within the page, like How-to at the top followed by Reference, with a ToC at the top. Given that we do not have a search bar on our site, the best you can do is ctrl+f to find within a page, which makes the user experience easier when you have fewer, larger pages.

I do think you could mitigate this concern a bit if you were to use copious amounts of cross-links between the two. For example, if I have a how-to that shows how to set configuration for a buildpack, you definitely want to link to the reference section that shows all of the configuration settings.

**Comment by andymoe** [comment]
Couple bits of context in regards to the feedback so far @dmikusa-pivotal and @arjun024 

1. We plan to add search across the entire site in the next phase of the redesign. 
2. I think we have plans to create a `web servers` top level buildpacks or similar so that might make sense to serve as a top level entry point on the docs site but for now we don't have something like that so I'd like to keep HTTPD and NGINX separate for now and revisit that when we prioritize that work or at least after we get the existing docs split up... so I'd like that to be out of scope for this PR.
3. Finally, right now, the intention is to start by splitting up existing docs, then consider where we need to augment them, and finally automate generation of reference materials. That last part will probably be easier to get started with if the how to's and reference docs are separate at least for the time being.

**Comment by fg-j** [comment]
@arjun024 and @dmikusa-pivotal – My initial process for splitting the docs was to separate the existing content somewhat logically with as few changes as possible. Things that weren't directly geared toward explaining how to achieve a specific outcome (like explaining the `detect` and `build` behaviour) I moved to Reference for now. 

In an ideal world // future state, the Reference documentation for the buildpack would look more like the screenshot below from the [Figma mockup](https://www.figma.com/file/vc91zvGMqGxY022FUoOm4S/Paketo_Web_0.01?node-id=189%3A350).

Notable contents of the future-state Reference docs are:
- an enumeration of _all_ of the environment variable config and binding options for the buildpack
- (for composite buildpacks) a list of all component buildpacks included
- (for component buildpacks) An explanation of the `detect` and `build` behaviour of the buildpack

 In a _really_ ideal world, these reference docs will be largely auto-generated based on the `buildpack.toml` (and maybe some other stuff). 

In the future, I think How Tos should look more like a bulleted/numbered series of steps that gets a user to an outcome, including copyable snippets. This will require some human re-writing.

Thus, in the future, I think the content of the How To and Reference pages will be quite distinct. For that reason @dmikusa-pivotal I hesitate to pull them back into a single page.

Regardless,  I think it's totally reasonable to want more linking between the Reference and How To docs. I can add that. I'm also open to combining HTTPD and NGINX into a single Web Servers How To page. That seems to align with an outcome-oriented approach to grouping How To docs.

I totally hear your concern about duplication @arjun024. I think I'll go back over this and generate a bit of net-new content to try and make the separation more clear.


image

**Comment by fg-j** [comment]
@dmikusa-pivotal and @arjun024 -- let me know what you think about this iteration. Didn't add too much new content, but tried to make the intent of the two docs types more clear.

**Comment by dmikusa-pivotal** [comment]
Looks good, thanks for reorganizing this!

**Review by andymoe — APPROVED** [review]

**Pull request merged**
