### PR TITLE
add automated checks

### PR DESCRIPTION
**Pull request by fg-j**
## Summary

Adds automated checks to help ensure docs/site quality
- Checks whether internal links in docs content are wrapped with `{{<ref>}}` shortcodes
- Checks whether all links in rendered site are valid
- Checks spelling of documentation
- Cron job checks for broken links on the live deployed paketo site every day at 0500

## Use Cases

Keep Paketo site at high quality without maintainers needing to bring a fine-toothed-comb to every aspect of every contribution, all of the time.

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by fg-j** [comment]
Moving to draft state because I've discovered a couple of bugs in the scripts.

**Comment by fg-j** [comment]
The links that fail Check LInks are anchor links on pages that run some JS to assign element IDs. Since `muffet` doesn't run any JS, it can't detect that these anchor links are correct. This [won't be fixed](https://github.com/raviqqe/muffet/issues/52) in `muffet` anytime soon.

**Comment by fg-j** [comment]
@simonjjones mentioned it might be a good idea to add a check to ensure links are using HTTPS and not HTTP, whenever possible. In the interest of getting this PR merged, I've called it out of scope for this one, but I've created #325 to track this.

**Comment by fg-j** [comment]
🤬  seems like NIST CPE search is down (https://nvd.nist.gov/products/cpe/search), but otherwise the automation has been updated to be green-by-default.

I think things are in a good state for review @ForestEckhardt .

**Review by ForestEckhardt — APPROVED** [review]

**Pull request merged**
